import { Temple } from '@/components/temple-card'

export const mockTemples: Temple[] = [
  {
    id: '1',
    name: 'Varanasi Kashi Vishwanath Temple',
    location: 'Varanasi',
    state: 'Uttar Pradesh',
    image: 'https://images.unsplash.com/photo-1599581423571-7d830c90c6b6?w=500&h=400&fit=crop',
    rating: 4.8,
    reviews: 2543,
    description: 'One of the holiest temples dedicated to Lord Shiva, situated on the banks of the Ganges River.',
    founded: 1776,
    deity: 'Lord Shiva',
    architecture: 'North Indian',
    facilities: ['Parking', 'Prasad', 'Donation Counter', 'Photography Zone'],
    visitingHours: '4:00 AM - 11:00 PM',
    bestTimeToVisit: 'November to February',
    entryFee: 'Free',
  },
  {
    id: '2',
    name: 'Meenakshi Temple',
    location: 'Madurai',
    state: 'Tamil Nadu',
    image: 'https://images.unsplash.com/photo-1599581423571-7d830c90c6b6?w=500&h=400&fit=crop',
    rating: 4.7,
    reviews: 1890,
    description: 'Ancient temple dedicated to Goddess Meenakshi, known for its stunning Dravidian architecture.',
    founded: 1500,
    deity: 'Goddess Meenakshi',
    architecture: 'South Indian',
    facilities: ['Temple Museum', 'Dining Hall', 'Water Facilities', 'Guide Services'],
    visitingHours: '5:00 AM - 10:00 PM',
    bestTimeToVisit: 'April to May',
    entryFee: 'Free',
  },
  {
    id: '3',
    name: 'Tirumala Venkateswara Temple',
    location: 'Tirupati',
    state: 'Andhra Pradesh',
    image: 'https://images.unsplash.com/photo-1599581423571-7d830c90c6b6?w=500&h=400&fit=crop',
    rating: 4.9,
    reviews: 3456,
    description: 'One of the richest temples in the world, dedicated to Lord Venkateswara. A must-visit pilgrimage site.',
    founded: 1150,
    deity: 'Lord Venkateswara',
    architecture: 'South Indian',
    facilities: ['Accommodation', 'Prasad Store', 'Medical Facility', 'Cloak Room', 'Banking'],
    visitingHours: '3:00 AM - 10:00 PM',
    bestTimeToVisit: 'November to January',
    entryFee: 'Free (Darshan Tokens: 50-300 INR)',
  },
  {
    id: '4',
    name: 'Jagannath Temple',
    location: 'Puri',
    state: 'Odisha',
    image: 'https://images.unsplash.com/photo-1599581423571-7d830c90c6b6?w=500&h=400&fit=crop',
    rating: 4.6,
    reviews: 2234,
    description: 'Sacred shrine dedicated to Lord Jagannath, famous for the annual Rath Yatra festival.',
    founded: 1161,
    deity: 'Lord Jagannath',
    architecture: 'Medieval',
    facilities: ['Prasad Distribution', 'Accommodation', 'Library', 'Photography Allowed in Select Areas'],
    visitingHours: '5:00 AM - 9:00 PM',
    bestTimeToVisit: 'June to August (Rath Yatra)',
    entryFee: 'Free',
  },
  {
    id: '5',
    name: 'Golden Temple',
    location: 'Amritsar',
    state: 'Punjab',
    image: 'https://images.unsplash.com/photo-1599581423571-7d830c90c6b6?w=500&h=400&fit=crop',
    rating: 4.8,
    reviews: 3890,
    description: 'The holiest shrine of Sikhism, known for its stunning golden dome and serene ambiance.',
    founded: 1604,
    deity: 'Sri Guru Granth Sahib',
    architecture: 'Modern',
    facilities: ['Langar (Free Meals)', 'Accommodation', 'Ablution Tanks', 'Museum', 'Guided Tours'],
    visitingHours: '24 Hours',
    bestTimeToVisit: 'October to March',
    entryFee: 'Free',
  },
  {
    id: '6',
    name: 'Khajuraho Temples',
    location: 'Khajuraho',
    state: 'Madhya Pradesh',
    image: 'https://images.unsplash.com/photo-1599581423571-7d830c90c6b6?w=500&h=400&fit=crop',
    rating: 4.5,
    reviews: 1567,
    description: 'UNESCO World Heritage site featuring stunning medieval temples with intricate sculptures.',
    founded: 1000,
    deity: 'Multiple (Brahma, Vishnu, Shiva)',
    architecture: 'Medieval',
    facilities: ['Museum', 'Guided Tours', 'Cafeteria', 'Restrooms'],
    visitingHours: '6:00 AM - 6:00 PM',
    bestTimeToVisit: 'October to March',
    entryFee: '250 INR (Indians), 500 INR (Foreigners)',
  },
  {
    id: '7',
    name: 'Rameshwaram Temple',
    location: 'Rameshwaram',
    state: 'Tamil Nadu',
    image: 'https://images.unsplash.com/photo-1599581423571-7d830c90c6b6?w=500&h=400&fit=crop',
    rating: 4.7,
    reviews: 2145,
    description: 'One of the four most important pilgrimage sites in India, dedicated to Lord Rama.',
    founded: 1600,
    deity: 'Lord Rama',
    architecture: 'South Indian',
    facilities: ['Bathing Tanks', 'Dining Hall', 'Accommodation', 'Prasad Store'],
    visitingHours: '4:00 AM - 9:00 PM',
    bestTimeToVisit: 'December to February',
    entryFee: 'Free',
  },
  {
    id: '8',
    name: 'Dwarka Temple',
    location: 'Dwarka',
    state: 'Gujarat',
    image: 'https://images.unsplash.com/photo-1599581423571-7d830c90c6b6?w=500&h=400&fit=crop',
    rating: 4.6,
    reviews: 1876,
    description: 'Ancient temple dedicated to Lord Krishna, situated at the western edge of India.',
    founded: 2500,
    deity: 'Lord Krishna',
    architecture: 'North Indian',
    facilities: ['Parking', 'Rest House', 'Prasad Counter', 'Donation Box'],
    visitingHours: '6:00 AM - 8:30 PM',
    bestTimeToVisit: 'November to February',
    entryFee: 'Free',
  },
  {
    id: '9',
    name: 'Somnath Temple',
    location: 'Somnath',
    state: 'Gujarat',
    image: 'https://images.unsplash.com/photo-1599581423571-7d830c90c6b6?w=500&h=400&fit=crop',
    rating: 4.4,
    reviews: 1234,
    description: 'One of the 12 Jyotirlingas dedicated to Lord Shiva, overlooking the Arabian Sea.',
    founded: 649,
    deity: 'Lord Shiva',
    architecture: 'Ancient',
    facilities: ['Beach Access', 'Prasad Distribution', 'Accommodation', 'Sound and Light Show'],
    visitingHours: '6:00 AM - 9:00 PM',
    bestTimeToVisit: 'November to January',
    entryFee: 'Free',
  },
  {
    id: '10',
    name: 'Kailash Temple',
    location: 'Ellora',
    state: 'Maharashtra',
    image: 'https://images.unsplash.com/photo-1599581423571-7d830c90c6b6?w=500&h=400&fit=crop',
    rating: 4.6,
    reviews: 1423,
    description: 'UNESCO World Heritage site with a monumental rock-cut temple dedicated to Lord Shiva.',
    founded: 750,
    deity: 'Lord Shiva',
    architecture: 'Ancient',
    facilities: ['Guided Tours', 'Rest Areas', 'Photography Zones', 'Museum'],
    visitingHours: '9:00 AM - 5:30 PM',
    bestTimeToVisit: 'October to March',
    entryFee: '250 INR (Indians), 500 INR (Foreigners)',
  },
  {
    id: '11',
    name: 'Arunachaleswara Temple',
    location: 'Arunachalam',
    state: 'Tamil Nadu',
    image: 'https://images.unsplash.com/photo-1599581423571-7d830c90c6b6?w=500&h=400&fit=crop',
    rating: 4.5,
    reviews: 987,
    description: 'Ancient temple dedicated to Lord Shiva, surrounded by the sacred Arunachala hill.',
    founded: 1400,
    deity: 'Lord Shiva',
    architecture: 'South Indian',
    facilities: ['Mountain Trek', 'Dining Hall', 'Accommodation', 'Pilgrim Services'],
    visitingHours: '4:00 AM - 9:00 PM',
    bestTimeToVisit: 'November to January',
    entryFee: 'Free',
  },
  {
    id: '12',
    name: 'Badrinath Temple',
    location: 'Badrinath',
    state: 'Uttarakhand',
    image: 'https://images.unsplash.com/photo-1599581423571-7d830c90c6b6?w=500&h=400&fit=crop',
    rating: 4.7,
    reviews: 2567,
    description: 'One of the four most sacred pilgrimage sites, dedicated to Lord Vishnu in the Himalayas.',
    founded: 1500,
    deity: 'Lord Vishnu',
    architecture: 'Ancient',
    facilities: ['Accommodation', 'Hot Springs', 'Dining Hall', 'First Aid'],
    visitingHours: '6:00 AM - 8:00 PM',
    bestTimeToVisit: 'April to May & September to October',
    entryFee: 'Free',
  },
]
